tensorflowkorea/tensorflow-kr

g3doc/get_started/basic_usage.md
get_started에서 ### Building the graph 번역 했습니다.
확인 부탁드립니다.
=> get_started에서 ### Building the graph 번역

g3doc/get_started/basic_usage.md
=> Correction errors2

g3doc/get_started/basic_usage.md
=> Omitting postposition

g3doc/api_docs/python/contrib.util.md
=> contrib.util.md 수정

g3doc/api_docs/python/contrib.util.md
=> contrib.util.md 수정추가

g3doc/api_docs/python/contrib.util.md
=> contrib.util.md 오타수정 및 내용추가

g3doc/tutorials/mnist/download/index.md
g3doc/tutorials/mnist/download 번역입니다.
=> Translate g3doc/tutorials/mnist/download

g3doc/contrib/learn/get_started/index.md
#75 작업해보았습니다. 영어 실력이 좋은 편은 아닌지라,, 제가 요즘 관심을 두고 있는  Tensorflow learn 기능에 관한 내용 번역입니다. (텍스트 자체가 워낙 적기도 해서,,,) 다음번에 좀 더 긴 번역에 도전해보겠습니다!
=> Tensorflow learn first commit

g3doc/how_tos/using_gpu/index.md
=> how_tos/using_gpu/index.md

g3doc/resources/bib.md
=> #86 commit

g3doc/api_docs/python/constant_op.md
=> Translate g3doc/api_docs/python/constant_op.md

g3doc/api_docs/python/string_ops.md
=> Trnaslate g3doc/api_docs/python/string_ops.md

g3doc/tutorials/linear/overview.md
=> Translate g3doc/tutorials/linear/overview.md

g3doc/api_docs/python/test.md
=> Translate g3doc/api_docs/python/test.md

g3doc/api_docs/python/script_ops.md
=> Translate g3doc/api_docs/python/script_ops.md

g3doc/resources/uses.md
=> #99 g3doc/resources/uses.md 완료했습니다.

g3doc/tutorials/syntaxnet/index.md
/g3doc/tutorials/syntaxnet/index.md 번역입니다. 해당 이슈는:
https://github.com/tensorflowkorea/tensorflow-kr/issues/108
=> /g3doc/tutorials/syntaxnet/index.md 번역

g3doc/get_started/basic_usage.md
주말에는 볼 시간이 없으니.. 평일에 두어 개 더 해봅니다.
=> /get_started/basic_usage.md 오타 수정 및 누락된 링크 추가

g3doc/resources/faq.md
=> #107 완료했습니다.

g3doc/contrib/learn/index.md
ISSUE : https://github.com/tensorflowkorea/tensorflow-kr/issues/123
=> Translate index.md

g3doc/api_docs/python/contrib.util.md
[원문링크](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/contrib.util.md)
=> /g3doc/api_docs/python/contrib.util.md 번역 추가 및 원문과 소소하게 상이한 부분 통일

g3doc/how_tos/tool_developers/index.md
=> Translate g3doc/how_tos/tool_developers/index.md

g3doc/api_docs/python/client.md
(#133)
기존 PR의 커밋로그가 지저분하여 다시 PR 보냅니다.
=> Translate g3doc/api_docs/python/client.md

g3doc/resources/glossary.md
=> Translate g3doc/resources/glossary.md

g3doc/resources/dims_types.md
=> g3doc/resources/dims_types.md 완료했습니다.

g3doc/resources/roadmap.md
=> /g3doc/resources/roadmap.md 번역

g3doc/how_tos/variables/index.md
=> g3doc/how_tos/variables/index.md 작업

g3doc/tutorials/wide_and_deep/index.md
=> g3doc/tutorials/wide_and_deep 완료

g3doc/tutorials/seq2seq/index.md
1. 오타 수정
2. 문장 번역 약간 수정
3. 링크 오류 수정
4. 남아있는 영어 원문 삭제
이 문서는 난이도가 있는 것인지 이해하기 무척 어렵네요...
=> /g3doc/tutorials/seq2seq/index.md trim

g3doc/tutorials/tflearn/index.md
=> /g3doc/tutorials/tflearn/index.md 링크 오류 수정 

g3doc/get_started/basic_usage.md
basic_usage.md 한 문장 번역 안 되어있는 것이 있길래 번역하였습니다.
=> basic_usage.md 한 문장

g3doc/how_tos/threading_and_queues/index.md
#188 번역 완료, 정리 아직 안됨(1~2일 소요일 것으로 예정)
=> g3doc/how-tos/threadingandqueues 번역 완료

g3doc/get_started/basic_usage.md
- 번역기 어투를 구어체로 변경
- 역주 일부 추가
- 혼란이 생길 수 있는 단어(graph 등)는 영어로만 표기 혹은 영어 병기
=> g3doc/get_started/basic_usage 재번역

g3doc/get_started/basic_usage.md
=> g3doc/get_started/basic_usage.md 오타 수정

g3doc/how_tos/adding_an_op/index.md
이대로 계속 번역해도 될가요 ..? (스스로의 번역에 자신감이 별로 없습니다 ^^;;)
=> 제가 잘 번역하고있는지 중간점검 해주시기 바랍니다.

g3doc/tutorials/word2vec/index.md
=> Fix typo `loos` -> `loss` #147
